config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :destroy, :update,] 

  resources :tweets do
    resources :comments, only: [:create, :edit, :update, :destroy, ]
  end

  root 'tweets#index'

  get 'tweets/new/:category' => 'tweets#new'

  get 'tweets/week' => 'tweets#week'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 }

  has_many :comments, dependent: :destroy

  has_one_attached :photo #追記
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :photo])
    end
  

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
        tweet = Tweet.find(params[:tweet_id])
        comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
        comment.user_id = current_user.id
        if comment.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path) #直前のページにリダイレクト
        else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path) #直前のページにリダイレクト
        end
    end

    def edit
        @tweet = Tweet.find(params[:tweet_id])
        @comment = @tweet.comments.find(params[:id])
    end
    
    def update
        comment = Comment.find(params[:id])
        @tweet = comment.tweet
        if comment.update(comment_params)
            redirect_to @tweet
        else
            redirect_to :action => "edit"
        end
    end
    
    def destroy
        @tweet = Tweet.find(params[:tweet_id])
        comment = @tweet.comments.find(params[:id])
        comment.destroy
        redirect_back(fallback_location: tweet_path)
    end
    
    private
        def comment_params
            params.require(:comment).permit(:content)
            #form tagにてpost_idパラメータを送信して、コメントへpost_idを格納するようにする必要がある。URLを作るために。
        end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

protect_from_forgery

    before_action :authenticate_user! # 追加

    def index
        @tweet = Tweet.all
        @jobsearch = Tweet.where(category:"jobsearch")
        @study = Tweet.where(category:"study")
        @university = Tweet.where(category:"university")
        @other = Tweet.where(category:"other")
        start_date = params.fetch(:start_date, Date.today).to_date
        @events = Tweet.where('start_time <= ? AND (end_time >= ? OR end_time IS NULL)', start_date.end_of_month.end_of_week, start_date.beginning_of_month.beginning_of_week)
    end

    def new
        @tweet = Tweet.new
        @category = params[:category]
        @events = Tweet.new
    end
    
    def create
        tweet = Tweet.new(tweet_params)
        if tweet.save!
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def show
        @tweet = Tweet.find(params[:id])
        @events = Tweet.find(params[:id])
        @comments = @tweet.comments
        @comment = Comment.new
    end

    def edit
        @tweet = Tweet.find(params[:id])
        @events = Tweet.find(params[:id])
    end

    def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
            redirect_to :action => "show", :id => tweet.id
        else
            redirect_to :action => "new"
        end
    end

    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to action: :index
    end

    def week
        @tweet = Tweet.all
        @jobsearch = Tweet.where(category:"jobsearch")
        @study = Tweet.where(category:"study")
        @university = Tweet.where(category:"university")
        @other = Tweet.where(category:"other")
        start_date = params.fetch(:start_date, Date.today).to_date
        @events = Tweet.where('start_time <= ? AND (end_time >= ? OR end_time IS NULL)', start_date.end_of_month.end_of_week, start_date.beginning_of_month.beginning_of_week)
    end
    
    private
    def tweet_params
        params.require(:tweet).permit(:thing, :date_date, :date_time, :address, :title, :content, :start_time, :end_time, :category, :cretaed_at, :updated_at)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
        @tweet = Tweet.all
        @jobsearch = Tweet.where(category:"jobsearch")
        @study = Tweet.where(category:"study")
        @university = Tweet.where(category:"university")
        @other = Tweet.where(category:"other")
    end

    def destroy
        user = User.find(params[:id])
        user.destroy
        redirect_to action: :index
    end

    private

    def user_params
        params.require(:user).permit(:title, :body, :photo) #photoを追加
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<div class="box2-1">
    <%= form_for(@comment, url: tweet_comment_path(@comment)) do |f| %>
        <%= f.label :"コメント内容" %>
        <p><%= f.text_field :content, :size => 60 %></p>
        <p><input type="submit" value="編集する" class="button"></p>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mycalendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollTrigger/1.0.3/ScrollTrigger.min.js"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.css"></script>
  </head>

  <body>
    <header>
      <div class="title">
        <h1>Mycalendar</h1>
        <h4>マイカレ。</h4>
      </div>

      <div class="header-list">
        <ul>
          <li><%= link_to "ホーム", tweets_path %></li>
          <li><%= link_to "新規投稿", new_tweet_path %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <li>
              <% if user_signed_in? %>
                <%= link_to "マイページ", user_path(current_user.id) %>
              <% end %>
          </li>
        </ul>
      </div>
    </header>
    
    <main>
      <%= yield %>
    </main>
    
    <footer>
      <h6>Copyright © GeekSalon All Rights Reserved.</h6>
    </footer>
  </body>
</html>

app/views/posts/index.html.erb
<div id='calendar'></div>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
<div class="field">
    <%= f.label :title,"予定名" %>
    <p><%= f.text_field :title, :size => 20 %></p>
    <%= f.label :color,"色選択" %>
    <p><%= f.color_field :color, :size => 20 %></p>
    <%= f.label :start_time,"始まり" %>
    <%= f.datetime_field :start_time %>
    <%= f.label :end_time,"終わり" %>
    <%= f.datetime_field :end_time %>
</div>
<%= f.submit "投稿" %>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tweets/edit.html.erb
<h1 class="theme">投稿編集</h1>
<div class="tweetedit">
  <div class="todoedit">
    <%= form_for @tweet do |f| %>
      <%= f.label :todo  %>
      <p><%= f.text_area :thing, :size => "30×2" %></p>
      <%= f.label :"日付"  %>
      <p><%= f.date_field :date_date, :size => 10 %></p>
      <%= f.label :"時刻"  %>
      <p><%= f.time_field :date_time, :size => 10 %></p>
      <%= f.label :"どこでする？"  %>
      <p><%= f.text_field :address, :size => 30 %></p>
      <p><input type="submit" value="編集する" class="button"></p>
    <% end %>
  </div>


  <div class="eventedit">
    <%= form_for @events do |f| %>
      <%= f.label :title %>
      <p><%= f.text_field :title %></p>
        <%= f.label :start_time, "いつから？" %>
          <p><%= f.date_field :start_time %></p>
          <%= f.label :end_time,"いつまで？/１日だけの予定の場合、未記入可" %>
          <p><%= f.date_field :end_time %></p>
      <p><input type="submit" value="編集する" class="button"></p>
    <% end %>
  </div>
</div>

<%= link_to "ホームに戻る", tweets_path, class:'button001' %>

app/views/tweets/index.html.erb
<div class="slidebox">
    <%= image_tag "C:/Users/81802/Desktop/mycalendar/app/assets/images/AdobeStock_405231145.jpeg",class:"sentotihiro"%>
    <%= image_tag "C:/Users/81802/Desktop/mycalendar/app/assets/images/AdobeStock_219384538.jpeg",class:"sentotihiro"%>
    <%= image_tag "C:/Users/81802/Desktop/mycalendar/app/assets/images/kouyou.jpeg",class:"sentotihiro"%>
    <%= image_tag "C:/Users/81802/Desktop/mycalendar/app/assets/images/1720014_m.jpg",class:"sentotihiro"%>
</div>
<div class="slide_textBox">
  <h1 class="slide_copy">予定を一目で</h1>
    <p class="slide_text">自己管理を簡単にする。</p>
</div>

<div class="container">
  <div class="todo">
    <h1 class="box-title">To Do リスト</h1>
      <h3>就活関連</h3>
        <div class="tweets-container">
          <% @jobsearch.each do |t| %>
            <div class="tweet">
              <%= t.thing %>
              <p><%= t.date_date %></p>
              <p><%= l t.date_time, format: :short, default: '' %></p>
              <p><%= t.address %></p>
              <%= link_to "詳細へ", tweet_path(t.id), class:'link' %>
              <%= link_to "編集する", edit_tweet_path(t.id), class:'link' %>
              <%= button_to "完了", tweet_path(t.id), method: :delete, class:'btn' %>
            </div>
          <% end %>
        </div>

      <h3>研究関連</h3>
        <div class="tweets-container">
          <% @study.each do |t| %>
            <div class="tweet">
              <%= t.thing %>
              <p><%= t.date_date %></p>
              <p><%= l t.date_time, format: :short, default: '' %></p>
              <p><%= t.address %></p>
              <%= link_to "詳細へ", tweet_path(t.id), class:'link' %>
              <%= link_to "編集する", edit_tweet_path(t.id), class:'link' %>
              <%= button_to "完了", tweet_path(t.id), method: :delete, class:'btn' %>
            </div>
          <% end %>
        </div>

      <h3>大学関連</h3>
        <div class="tweets-container">
          <% @university.each do |t| %>
            <div class="tweet">
              <%= t.thing %>
              <p><%= t.date_date %></p>
              <p><%= l t.date_time, format: :short, default: '' %></p>
              <p><%= t.address %></p>
              <%= link_to "詳細へ", tweet_path(t.id), class:'link' %>
              <%= link_to "編集する", edit_tweet_path(t.id), class:'link' %>
              <%= button_to "完了", tweet_path(t.id), method: :delete, class:'btn' %>
            </div>
          <% end %>
        </div>

      <h3>その他</h3>
        <div class="tweets-container">
          <% @other.each do |t| %>
            <div class="tweet">
              <%= t.thing %>
              <p><%= t.date_date %></p>
              <p><%= l t.date_time, format: :short, default: '' %></p>
              <p><%= t.address %></p>
              <%= link_to "詳細へ", tweet_path(t.id), class:'link' %>
              <%= link_to "編集する", edit_tweet_path(t.id), class:'link' %>
              <%= button_to "完了", tweet_path(t.id), method: :delete, class:'btn' %>
            </div>
          <% end %>
        </div>
  </div>

    <div class="calendar">
      <%= month_calendar(attribute: :start_time, start_attribute: :start_time, end_attribute: :end_time, events: @events) do |date, events| %>
          <%= date %>
        <% events.each do |event| %>
          <p><%= link_to event.title, event %></p>
        <% end %>
      <% end %>
    </div>

</div>

app/views/tweets/new.html.erb
<div class="newtweet">
    <h1><div class="theme">新規投稿</div></h1>

    <div class="new">
        <div class="todoall">
            <div class="newtodo">
                <h2 class="newtitle">todo 投稿</h2>
                    <%= form_for @tweet do |f| %>
                        <div class="field">
                            <div class="Thing_field">         <%#データ型がstringで自由記述の入力フォーム %>
                                <%= f.label :Todo  %>
                                    <p><%= f.text_area :thing, :size => "30×2" %></p>
                            </div>
                            <div class="todo_time">
                                <div class="Date_field">         <%#データ型がintegerで数字のみを入力するフォーム %>
                                    <%= f.label :"日付"  %>
                                        <p><%= f.date_field :date_date, :size => 10 %></p>
                                </div>
                                <div class="Time_field">         <%# データ型がintegerで数字のみを入力するフォーム %>
                                    <%= f.label :"時刻"  %>
                                        <p><%= f.time_field :date_time, :size => 10 %></p>
                                </div>
                            </div>
                            <div class="Adress_field">        <%# データ型がtextで自由記述の入力フォーム %>
                                <%= f.label :"どこでする？"  %>
                                    <p><%= f.text_field :address, :size => 30 %></p>
                            </div>
                            <%= f.label :"カテゴリー"  %>
                            <p><%= f.select :category, [["就活", "jobsearch"], ["研究", "study"], ["大学", "university"], ["その他", "other"]], include_blank: "選択してください" %></p>
                        </div>
                        <p><input type="submit" value="投稿" class="button"></p>
                    <% end %>
            </div>
        
            <div class="text1">やることの可視化で後回しを減らす。</div>
        </div>

        <div class="eventall">
            <div class="event">
                <h2 class="newtitle">イベント投稿</h2>
                    <%= form_with(model: @events, local: true) do |form| %>
                        <div class="field">
                            <div class="event_title">
                                <%= form.label :title %>
                                <p><%= form.text_field :title %></p>
                            </div>
                            <div class="time">
                                <%= form.label :start_time,"いつから？" %>
                                <p><%= form.date_field :start_time %></p>
                                <%= form.label :end_time,"いつまで？/１日だけの予定の場合、未記入可" %>
                                <p><%= form.date_field :end_time %></p>
                            </div>
                        </div>
                            <input type="submit" value="投稿" class="button">
                    <% end %>
            </div>

            <div class="text2">日々の生活を彩る。</div>
        </div>
    </div>

    <%= link_to "ホームに戻る", tweets_path, class:'button001' %>

</div>

app/views/tweets/show.html.erb
<h1 class="theme">投稿詳細</h1>
    <div class="detail">
        <div class="tododetail">
            <h2>To Do</h2>
                    <div class="tweet">
                        <%= @tweet.thing %>
                        <p><%= @tweet.date_date %></p>
                        <p><%= l @tweet.date_time, format: :short, default: '' %></p>
                        <p><%= @tweet.address %></p>
                    </div>
            <p><%= link_to "編集する", edit_tweet_path(@tweet.id) %></p>
            <p><%= button_to "完了", tweet_path(@tweet.id), method: :delete, class:'btn' %></p>
        
            <div class="comment-wrapper">
                <div class="comment">
                    <p>コメント一覧</p>
                </div>
                <% @comments.each do |c| %>
                    <div>
                    <%= c.content %>
                    <p><%= link_to "編集する", edit_tweet_comment_path(@tweet,c) %></p>
                    <%= button_to "削除する", tweet_comment_path(@tweet,c), method: :delete %>
                    </div>
                    <br>
                <% end %>

                <% if user_signed_in? %>
                    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
                        <%= f.text_area :content %>
                        <%= button_tag type: "submit" do %>
                            <i class="far fa-comments"></i> コメントする
                        <% end %>
                    <% end %>
                <% end %>
            </div>
        </div>

        <div class="eventdetail">
            <h2>イベント</h2>
                    <div class="eventtitle">
                        <%= @events.title %>
                    </div>
            <p><%= link_to "編集する", edit_tweet_path(@events.id) %></p>
            <p><%= button_to "削除する", tweet_path(@events.id), method: :delete %></p>
        </div>
</div>

<%= link_to "ホームに戻る", tweets_path, class:'button001' %>

app/views/tweets/week.html.erb
<div class="container">
    <div class="todo">
        <h1>To Do リスト</h1>
            <h3>就活関連</h3>
                <div class="tweets-container">
                    <% @jobsearch.each do |t| %>
                        <div class="tweet">
                            <%= t.thing %>
                            <%= t.date_date %>
                            <%= t.date_time %>
                            <%= t.address %>
                            <%= link_to "詳細へ", tweet_path(t.id) %>
                            <%= link_to "編集する", edit_tweet_path(t.id) %>
                            <%= button_to "削除する", tweet_path(t.id), method: :delete %>
                        /div>
                    <% end %>
                </div>

            <h3>研究関連</h3>
                <div class="tweets-container">
                    <% @study.each do |t| %>
                        <div class="tweet">
                            <%= t.thing %>
                            <%= t.date_date %>
                            <%= t.date_time %>
                            <%= t.address %>
                            <%= link_to "詳細へ", tweet_path(t.id) %>
                            <%= link_to "編集する", edit_tweet_path(t.id) %>
                            <%= button_to "削除する", tweet_path(t.id), method: :delete %>
                        </div>
                    <% end %>
                </div>

            <h3>大学関連</h3>
                <div class="tweets-container">
                    <% @university.each do |t| %>
                        <div class="tweet">
                            <%= t.thing %>
                            <%= t.date_date %>
                            <%= t.date_time %>
                            <%= t.address %>
                            <%= link_to "詳細へ", tweet_path(t.id) %>
                            <%= link_to "編集する", edit_tweet_path(t.id) %>
                            <%= button_to "削除する", tweet_path(t.id), method: :delete %>
                        </div>
                    <% end %>
                </div>

            <h3>その他</h3>
                <div class="tweets-container">
                    <% @other.each do |t| %>
                        <div class="tweet">
                            <%= t.thing %>
                            <%= t.date_date %>
                            <%= t.date_time %>
                            <%= t.address %>
                            <%= link_to "詳細へ", tweet_path(t.id) %>
                            <%= link_to "編集する", edit_tweet_path(t.id) %>
                            <%= button_to "削除する", tweet_path(t.id), method: :delete %>
                        </div>
                    <% end %>
                </div>
    </div>

        <p data-trigger class="opacityFadeIn">
            <%= week_calendar(attribute: :start_time, start_attribute: :start_time, end_attribute: :end_time, events: @events) do |date, events| %>
                <%= date %>
                    <% events.each do |event| %>
                        <p><%= link_to event.title, event %></p>
                <% end %>
            <% end %>
        </p>
    </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="profileall">
  <div class="profiledetail">
    <div class="shinchokuritu">
      <h1 class="graph">Todo残量</h1>
        <p>※何も表示されなければGood👍</p>
      <canvas id="myChart"></canvas>
        <script>
        var ctx = document.getElementById("myChart");
        var myChart = new Chart(ctx, {
          type: 'radar',
          data: {
            labels: ["就活", "研究", "大学", "その他"],
            datasets: 
            [
              {
                label: 'Todo 残量',
                backgroundColor: 'rgba(128,128,128,0.5)',
                borderColor: 'rgba(128,128,128,1.0)',
                data: [<%= @jobsearch.count %>, <%= @study.count %>, <%= @university.count %>, <%= @other.count %>]
                }
            ]
          },
          options: {
              scale: {
                  ticks: {
                      suggestedMin: 0,
                      suggestedMax: 5
                  }
              }
          }
        });
        </script>
    </div>

    <div class="profile">
      <% if @user.photo.attached? %>
        <%= image_tag @user.photo, class: "rounded-circle", size: '90x120'%>
      <% end %>

      <h1 class="box-title">profile</h1>
        <p>名前 : <%= @user.name %></p>
        <p>メールアドレス : <%= @user.email %></p>
        <p>プロフィール : <%= @user.profile %></p>
      <% if current_user.id == @user.id %>
        <%= link_to "編集する", edit_user_registration_path %>
      <% end %>
    </div>
  </div>
</div>

<p><%= link_to "ホームに戻る", tweets_path, class:'button001' %></p>